/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionPatientIdRouteImport } from './routes/session.$patientId'
import { Route as PatientPatientIdRouteImport } from './routes/patient.$patientId'
import { Route as EvolutionPatientIdRouteImport } from './routes/evolution.$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionPatientIdRoute = SessionPatientIdRouteImport.update({
  id: '/session/$patientId',
  path: '/session/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPatientIdRoute = PatientPatientIdRouteImport.update({
  id: '/patient/$patientId',
  path: '/patient/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolutionPatientIdRoute = EvolutionPatientIdRouteImport.update({
  id: '/evolution/$patientId',
  path: '/evolution/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evolution/$patientId': typeof EvolutionPatientIdRoute
  '/patient/$patientId': typeof PatientPatientIdRoute
  '/session/$patientId': typeof SessionPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evolution/$patientId': typeof EvolutionPatientIdRoute
  '/patient/$patientId': typeof PatientPatientIdRoute
  '/session/$patientId': typeof SessionPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evolution/$patientId': typeof EvolutionPatientIdRoute
  '/patient/$patientId': typeof PatientPatientIdRoute
  '/session/$patientId': typeof SessionPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/evolution/$patientId'
    | '/patient/$patientId'
    | '/session/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/evolution/$patientId'
    | '/patient/$patientId'
    | '/session/$patientId'
  id:
    | '__root__'
    | '/'
    | '/evolution/$patientId'
    | '/patient/$patientId'
    | '/session/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvolutionPatientIdRoute: typeof EvolutionPatientIdRoute
  PatientPatientIdRoute: typeof PatientPatientIdRoute
  SessionPatientIdRoute: typeof SessionPatientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$patientId': {
      id: '/session/$patientId'
      path: '/session/$patientId'
      fullPath: '/session/$patientId'
      preLoaderRoute: typeof SessionPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/$patientId': {
      id: '/patient/$patientId'
      path: '/patient/$patientId'
      fullPath: '/patient/$patientId'
      preLoaderRoute: typeof PatientPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolution/$patientId': {
      id: '/evolution/$patientId'
      path: '/evolution/$patientId'
      fullPath: '/evolution/$patientId'
      preLoaderRoute: typeof EvolutionPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvolutionPatientIdRoute: EvolutionPatientIdRoute,
  PatientPatientIdRoute: PatientPatientIdRoute,
  SessionPatientIdRoute: SessionPatientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
