/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionPatientIdRouteImport } from './routes/session.$patientId'
import { Route as PeiPatientIdRouteImport } from './routes/pei.$patientId'
import { Route as PatientPatientIdRouteImport } from './routes/patient.$patientId'
import { Route as EvolutionPatientIdRouteImport } from './routes/evolution.$patientId'
import { Route as AdminHoursRouteImport } from './routes/admin.hours'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'

const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionPatientIdRoute = SessionPatientIdRouteImport.update({
  id: '/session/$patientId',
  path: '/session/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const PeiPatientIdRoute = PeiPatientIdRouteImport.update({
  id: '/pei/$patientId',
  path: '/pei/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPatientIdRoute = PatientPatientIdRouteImport.update({
  id: '/patient/$patientId',
  path: '/patient/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolutionPatientIdRoute = EvolutionPatientIdRouteImport.update({
  id: '/evolution/$patientId',
  path: '/evolution/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHoursRoute = AdminHoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/forum': typeof ForumRoute
  '/parent': typeof ParentRoute
  '/patients': typeof PatientsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/hours': typeof AdminHoursRoute
  '/evolution/$patientId': typeof EvolutionPatientIdRoute
  '/patient/$patientId': typeof PatientPatientIdRoute
  '/pei/$patientId': typeof PeiPatientIdRoute
  '/session/$patientId': typeof SessionPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/forum': typeof ForumRoute
  '/parent': typeof ParentRoute
  '/patients': typeof PatientsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/hours': typeof AdminHoursRoute
  '/evolution/$patientId': typeof EvolutionPatientIdRoute
  '/patient/$patientId': typeof PatientPatientIdRoute
  '/pei/$patientId': typeof PeiPatientIdRoute
  '/session/$patientId': typeof SessionPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/forum': typeof ForumRoute
  '/parent': typeof ParentRoute
  '/patients': typeof PatientsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/hours': typeof AdminHoursRoute
  '/evolution/$patientId': typeof EvolutionPatientIdRoute
  '/patient/$patientId': typeof PatientPatientIdRoute
  '/pei/$patientId': typeof PeiPatientIdRoute
  '/session/$patientId': typeof SessionPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agenda'
    | '/forum'
    | '/parent'
    | '/patients'
    | '/admin/approvals'
    | '/admin/hours'
    | '/evolution/$patientId'
    | '/patient/$patientId'
    | '/pei/$patientId'
    | '/session/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agenda'
    | '/forum'
    | '/parent'
    | '/patients'
    | '/admin/approvals'
    | '/admin/hours'
    | '/evolution/$patientId'
    | '/patient/$patientId'
    | '/pei/$patientId'
    | '/session/$patientId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agenda'
    | '/forum'
    | '/parent'
    | '/patients'
    | '/admin/approvals'
    | '/admin/hours'
    | '/evolution/$patientId'
    | '/patient/$patientId'
    | '/pei/$patientId'
    | '/session/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgendaRoute: typeof AgendaRoute
  ForumRoute: typeof ForumRoute
  ParentRoute: typeof ParentRoute
  PatientsRoute: typeof PatientsRoute
  EvolutionPatientIdRoute: typeof EvolutionPatientIdRoute
  PatientPatientIdRoute: typeof PatientPatientIdRoute
  PeiPatientIdRoute: typeof PeiPatientIdRoute
  SessionPatientIdRoute: typeof SessionPatientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$patientId': {
      id: '/session/$patientId'
      path: '/session/$patientId'
      fullPath: '/session/$patientId'
      preLoaderRoute: typeof SessionPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pei/$patientId': {
      id: '/pei/$patientId'
      path: '/pei/$patientId'
      fullPath: '/pei/$patientId'
      preLoaderRoute: typeof PeiPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/$patientId': {
      id: '/patient/$patientId'
      path: '/patient/$patientId'
      fullPath: '/patient/$patientId'
      preLoaderRoute: typeof PatientPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolution/$patientId': {
      id: '/evolution/$patientId'
      path: '/evolution/$patientId'
      fullPath: '/evolution/$patientId'
      preLoaderRoute: typeof EvolutionPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hours': {
      id: '/admin/hours'
      path: '/hours'
      fullPath: '/admin/hours'
      preLoaderRoute: typeof AdminHoursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminHoursRoute: typeof AdminHoursRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminHoursRoute: AdminHoursRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgendaRoute: AgendaRoute,
  ForumRoute: ForumRoute,
  ParentRoute: ParentRoute,
  PatientsRoute: PatientsRoute,
  EvolutionPatientIdRoute: EvolutionPatientIdRoute,
  PatientPatientIdRoute: PatientPatientIdRoute,
  PeiPatientIdRoute: PeiPatientIdRoute,
  SessionPatientIdRoute: SessionPatientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
